import { golosText, inter } from '@/app/fonts'
import type { Metadata } from 'next'
import './globals.scss'
import { Providers } from '@/entities/providers/providers'
import { cn } from '@/shared/lib/utils/cn'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={cn(golosText.variable, inter.variable)}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
